name: ap_mediation_sdk
description: "Ap Mediation Demand Plugin for Flutter by AdPushup"
version: 0.1.0
homepage: https://github.com/adpushup/AdMobApMediationSdkFlutter

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.adpushup.ap_mediation_sdk
        pluginClass: ApMediationSdkPlugin
